version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - mongodb
      - mysql
    environment:
      - DB_URL_PG=postgres://user:password@postgres:5432/mydb
      - DB_URL_MONGO=mongodb://user:password@mongodb:27017/mydb
      - DB_URL_MYSQL=mysql://user:password@mysql:3306/mydb
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: .
          target: /app
          action: sync

  db-helsinki:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '54321:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/helsinki.sql:/docker-entrypoint-initdb.d/2_data.sql

  db-stockholm:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '54322:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/stockholm.sql:/docker-entrypoint-initdb.d/2_data.sql

  db-copenhagen:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '54323:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/copenhagen.sql:/docker-entrypoint-initdb.d/2_data.sql
