version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - mongodb
      - mysql
    environment:
      - DB_URL_PG=postgres://user:password@postgres:5432/mydb
      - DB_URL_MONGO=mongodb://user:password@mongodb:27017/mydb
      - DB_URL_MYSQL=mysql://user:password@mysql:3306/mydb
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: .
          target: /app
          action: sync

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./db/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - '27017:27017'

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - ./db/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
